### PR TITLE
I have de-commented the code.

### PR DESCRIPTION
**Pull request by AngelCIICMorales**
I just made the graphs render properly so my team may work on them.

### CODE REVIEW

**Review by fernandopizarro1 — CHANGES_REQUESTED** [review]
image
The show expense button right now does nothing, are we going to remove it or use it?

**Comment by AngelCIICMorales** [comment]
# @fernandopizarro1 I'm not sure if it's going to be fixed in the future.

**Comment by fernandopizarro1** [comment]
> # @fernandopizarro1 I'm not sure if it's going to be fixed in the future.

So should we comment it for now or should we leave it as it is?

**Review by fernandopizarro1 — APPROVED** [review]
That button should be addresed in the future, however this looks good to me!

**Review by NathBat09 — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
