### PR TITLE
Toggle button for viewing Expenses and Encomes in Bar Chart

### PR DESCRIPTION
**Pull request by jonVargas1**
This is for the toggle button for the bar chart. It will allow the user to toggle between their incomes and expenses for each month and the current year. 
Screen Shot 2024-04-20 at 12 20 31 PM

It also verifies for duplicate income, adding their amounts up.
Screen Shot 2024-04-20 at 12 20 48 PM
Screen Shot 2024-04-20 at 12 20 57 PM

### CODE REVIEW

**Comment by jonVargas1** [comment]
It now ignores the letter case of the income descriptions.
Screen Shot 2024-04-20 at 7 53 20 PM
Screen Shot 2024-04-20 at 7 51 21 PM

**Review by NathBat09 — APPROVED** [review]
LGTM!

**Review by fernandopizarro1 — CHANGES_REQUESTED** [review]
It seems that you changed the layout of the button and now the button is broken for the diverging bar chart. 
image_2024-04-21_095436150
Everything else looks good!

**Comment by jonVargas1** [comment]
@fernandopizarro1 Yeah my bad. Ya se lo arreglé.

**Review by fernandopizarro1 — APPROVED** [review]
image_2024-04-21_113052529
image_2024-04-21_113337272
LGTM!

**Pull request merged**
