### PR TITLE
#255 Finished Timed Diverging Bar Chart

### LINKED ISSUE #110: Data Visualization: Divergent Chart Custom Aesthetic
Within the intuitive interface, users possess the creative freedom to personalize their graphs extensively. By customizing colors and integrating captivating visual effects, users can craft a visually immersive experience tailored to their preferences and aesthetic sensibilities.

The color palette becomes a canvas for expression, enabling users to evoke emotions, emphasize trends, and highlight significant data points with precision. Whether opting for vibrant hues to convey positivity or subdued tones to denote stability, the ability to customize colors empowers users to align their visual representation with their unique storytelling objectives.

Moreover, the inclusion of visual effects elevates the graphical presentation to new heights of engagement. From subtle animations that add dynamism to static data points to sophisticated transitions that enhance data comprehension, users can imbue their graphs with a sense of fluidity and depth, transforming statistical analysis into a captivating journey of discovery.

This rich customization feature not only enhances visual appeal but also fosters deeper engagement and comprehension. By empowering users to infuse their graphs with personality and style, the platform transcends mere data visualization, becoming a conduit for creativity and expression in the exploration of financial insights.

Priority: 3
Difficulty: 5

### PR DESCRIPTION
**Pull request by fernandopizarro1**
Finished the implementation of a timed diverging bar chart with some added visuals:

image_2024-04-09_101310056
Added a total that is calculated depending on the filtered data. Added a visual that when hovering over a bar, it enhances the amount and the color is changed to green if the value is positive

image_2024-04-09_101453749
Added a different visual to change the color to red if the value is negative when hovering over the bar.

image_2024-04-09_101759871
If there is no information available, then this message will pop up.

### CODE REVIEW

**Comment by NathBat09** [comment]
It looks great, but I think there is a little bug when adding a new expense, it doesnt update inmediately. You have to click other graph or refresh to see in the diverging bar chart @fernandopizarro1:
image
image
image

**Comment by fernandopizarro1** [comment]
> It looks great, but I think there is a little bug when adding a new expense, it doesnt update inmediately. You have to click other graph or refresh to see in the diverging bar chart @fernandopizarro1: image image image

That's weird, I implemented soemthing for that exactly, let me check again and see if I missed something

**Comment by fernandopizarro1** [comment]
@NathBat09 I seem to have fixed the problem, can you try again?

**Review by NathBat09 — APPROVED** [review]
Looks great! 

image

**Review by AngelCIICMorales — APPROVED** [review]
LGTM!

**Pull request merged**
