### PR TITLE
Basic Bar Chart

### PR DESCRIPTION
**Pull request by fernandopizarro1**
This is a basic BarChart that uses D3. 
REMINDER: Please install D3, to do this just write on the terminal "npm install d3".

### CODE REVIEW

**Comment by Cruiz102** [comment]
I'm getting this error when trying to run the project. If you are using D3.js, download the package through node.js. The `package.json` file needs to be updated.
image

**Comment by fernandopizarro1** [comment]
> I'm getting this error when trying to run the project. If you are using D3.js, download the package through node.js. The `package.json` file needs to be updated. image

You have to download the d3 library in order for it to work. Just write “mpn install d3” in the terminal

**Comment by fernandopizarro1** [comment]
> > I'm getting this error when trying to run the project. If you are using D3.js, download the package through node.js. The `package.json` file needs to be updated. image
> 
> You have to download the d3 library in order for it to work. Just write “mpn install d3” in the terminal

“Npm”***

**Comment by Cruiz102** [comment]
Take this forum answer into consideration for adding d3.js in the package.json file.
https://stackoverflow.com/questions/47806605/adding-other-libraries-in-react-js-app

**Comment by NathBat09** [comment]
image

I worked, I had to install d3 as a dependency in the project. Just ran npm install d3 and it worked.

**Review by Cruiz102 — APPROVED** [review]
LGTM

**Review by diegoq48 — APPROVED** [review]
lgtm

**Pull request merged**
