### PR TITLE
Monthly budget visualizer & Filters 

### PR DESCRIPTION
**Pull request by fernandopizarro1**
- Added monthly and yearly filters 
- Added a progress bar 
- Added Montly Budget to use with the progress bar and the total of the filtered Expenses 
- Added Button Demo to add or update a monthly budget

### CODE REVIEW

**Comment by NathBat09** [comment]
@fernandopizarro1 did you have a similar problem with this at the beginning? In that case, how did you fix it? (I did the usual "bash", "npm install", "npm run dev"). Maybe some dependencies are needed.

image

**Comment by fernandopizarro1** [comment]
That's weird. I did not use any new dependencies, I only updated next.js 
The dates are built in with javascript, and .toMillis() converts it to milliseconds. Let me see if I can find the problem.

**Review by AngelCIICMorales — APPROVED** [review]
It works

**Comment by fernandopizarro1** [comment]
Hey @NathBat09, can you please recheck the code with the new commits? I believe I fixed the problem with the dates.

**Review by NathBat09 — APPROVED** [review]
Looks good to me!

image

**Pull request merged**
