### PR TITLE
Time-Based Bar Chart

### PR DESCRIPTION
**Pull request by jonVargas1**
This is to add a time-based bar chart. The user now has the ability to select a specific month to view their expenses for whichever month they choose. 
Screen Shot 2024-04-03 at 10 46 18 PM
Screen Shot 2024-04-03 at 10 46 01 PM

It also provides an option to view the expenses for the entire year.
Screen Shot 2024-04-03 at 10 46 36 PM

Currently, if the user selects a month that does not have any expenses it will not render a graph.
Screen Shot 2024-04-03 at 10 46 46 PM

### CODE REVIEW

**Review by fernandopizarro1 — COMMENTED** [review]
Hey @jonVargas1, I think a good change would be to make a message appear when the user does not have any data in that month, tell me what you think. But everything else looks good!

**Comment by jonVargas1** [comment]
@fernandopizarro1 Yeah that was my bad for not thinking about that. I have updated it so that it now should give the user the following message:
Screen Shot 2024-04-04 at 7 49 44 PM

**Comment by jonVargas1** [comment]
I also added an "All" option to view all the expenses the user has added and fixed a bug where it would show all the user's expenses when selecting the current year's expenses

**Review by NathBat09 — COMMENTED** [review]
Sorry, could you check again the text that appears when there is no data? @jonVargas1 

image


When you enter to the page or when you click other month without data, it doesnt appear. Just when you click All it appears in the other months too. You can fix that bug in other issue tho, however you want

**Review by NathBat09 — APPROVED** [review]
LGTM!
image
image
image

**Pull request merged**
