### PR TITLE
Table Analysis Modal

### PR DESCRIPTION
**Pull request by Fernando2908**
### **Fernando J. Sierra Aponte**
**_Daily income pattern - data analysis #140_**
- Create a table to calculate and display the total income for the day. Include relevant statistics like average, mean, median standard.

**_Weekly income pattern - data analysis #141_**
- Create a table to calculate and display the total income for the week. Include relevant statistics like average, mean, median standard.

**_Monthly income pattern - data analysis #142_**
- Create a table to calculate and display the total income for the month. Include relevant statistics like average, mean, median standard.

Screenshot 2024-03-21 at 2 13 39 PM

### **Onnelle Lugo Rodríguez**
**_Daily spending pattern - data analysis #136_**
- Create a table to calculate and display the total spending for the day. Include relevant statistics like average, mean, median standard.

**_Monthly spending patter - data analysis #137_**
- Create a table to calculate and display the total spending for the month. Include relevant statistics like average, mean, median standard.

**_Weekly spending patterns - data analysis #138_**
- Create a table to calculate and display the total spending for the week. Include relevant statistics like average, mean, median standard.
Screenshot 2024-03-21 at 2 15 34 PM

### CODE REVIEW

**Comment by fernandopizarro1** [comment]
Hey @Fernando2908 @Lennon0926 , I made some similar filters which I separated into a file to use on the progress bar and to be available to everybody,  so that you don't have to make the filters again. I mention this in case you want to use these filters and maybe add a few of your own, it would really help us to use these filters for our calendar when dealing with events.

**Comment by Lennon0926** [comment]
Hey @fernandopizarro1, I think you're right, it's awesome to have them available for everyone. Once your branch is merged with the main, I'll make sure to update the `moneyFilters.js` file to add them for general use.

**Comment by fernandopizarro1** [comment]
> Hey @fernandopizarro1, I think you're right, it's awesome to have them available for everyone. Once your branch is merged with the main, I'll make sure to update the `moneyFilters.js` file to add them for general use.

I think it already has been merged, please check the main branch to see if you can pull the changes.

**Comment by Lennon0926** [comment]
I have completed refactoring the methods and have added them to `moneyFilters.js`.

**Review by Cruiz102 — APPROVED** [review]
LGTM

**Review by JeanMontesSantiago — APPROVED** [review]

**Pull request merged**
