### PR TITLE
Changed pie chart to be a dynamic donut chart

### PR DESCRIPTION
**Pull request by NathBat09**
- Changed pie chart to be a donut chart

image

- By hovering each zone of the pie chart being able to see percentage of each categories

- The total amount of money expended is displayed in the center when is not hovered

- Interactive highlighting of each category by hovering

### CODE REVIEW

**Review by fernandopizarro1 — APPROVED** [review]
This looks great! There doesn't seem to be any issues and it uses my data.

**Comment by NathBat09** [comment]
Fixed bug by found by AngelCIICMorales. It had a rendering problem whenever a new expense was added, I think it's fixed.

**Review by fernandopizarro1 — CHANGES_REQUESTED** [review]
There is still a problem when adding a new expense. It happened to me to in the dynamic divergent chart, you have to delete the old chart before creating a new chart. 
Try using this before creating the svg:
`d3.select(svgRef.current).selectAll('*').remove();`

**Comment by NathBat09** [comment]
@fernandopizarro1 did you try it with the new commit? I added that line

**Review by AngelCIICMorales — APPROVED** [review]
I tested the new code and it works. LGTM.

**Review by fernandopizarro1 — APPROVED** [review]
Tested it our with that line and it works properly! LGTM

**Pull request merged**
