### PR TITLE
Calendar systems: interactive tiles to add incoming events and expected expenses 

### PR DESCRIPTION
**Pull request by NathBat09**
Objective:

Enhance the calendar system by having interactive tile that allows the user to manage future expenses.

Features:

Being able to store inputs from the user in the day tiles by clicking it, specifically for future events where the user expect to spend money. The user can see the event tag in the tile where a event is added and being able to see them when clicked.

The format will be:

-Title of the event (Ex. Shopping)
-Expected expenses 

(It's not connected to the database)

### CODE REVIEW

**Review by AngelCIICMorales — APPROVED** [review]
It has some minor bugs but since I'm going to work on improving the feature ill approve the pull request.

**Comment by fernandopizarro1** [comment]
> It has some minor bugs but since I'm going to work on improving the feature ill approve the pull request.

What exactly are the minor bugs that you are going to be working on?

**Comment by AngelCIICMorales** [comment]
I'm going to fix the fact that the event creation forum doesn't close when created and I'm going to add the data added to the calendar to the data base.

**Review by fernandopizarro1 — APPROVED** [review]
If this is focused more on frontend then LGTM.

Now it's just to add the data to the database and close the submit button appropiately.

**Comment by NathBat09** [comment]
> I'm going to fix the fact that the event creation forum doesn't close when created and I'm going to add the data added to the calendar to the data base.

@AngelCIICMorales more like a bug, that was intended (so I can change the event at the moment), but I can change it to disappear now that Im going to use buttons

**Comment by AngelCIICMorales** [comment]
@NathBat09 don't worry about the event bug since I'm already on it myself.

**Pull request merged**
